=== barnikola/OTVRAC/lab3/schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "default": [],
  "title": "Esports timovi i igrači",
  "description": "Skup esports timova i igrača za kolegij Otvoreno računarstvo",
  "required": [
    "Naziv",
    "Zemlja",
    "Godina_osnutka",
    "Skracenica",
    "Esport",
    "Broj_trofeja",
    "Pobjede2023",
    "Porazi2023",
    "Regija",
    "Ukupna_zarada",
    "Igraci"
  ],
  "properties": {
    "Naziv": {
      "type": "string",
      "title": "The Naziv Schema",
      "examples": [
        "T1"
      ]
    },
    "Zemlja": {
      "type": "string",
      "title": "The Zemlja Schema",
      "examples": [
        "Južna Koreja"
      ]
    },
    "Godina_osnutka": {
      "type": "string",
      "title": "The Godina_osnutka Schema",
      "examples": [
        "2003"
      ]
    },
    "Skracenica": {
      "type": "string",
      "title": "The Skracenica Schema",
      "examples": [
        "T1"
      ]
    },
    "Esport": {
      "type": "string",
      "title": "The Esport Schema",
      "examples": [
        "League of Legends"
      ]
    },
    "Broj_trofeja": {
      "type": "string",
      "title": "The Broj_trofeja Schema",
      "examples": [
        "10"
      ]
    },
    "Pobjede2023": {
      "type": "string",
      "title": "The Pobjede2023 Schema",
      "examples": [
        "96"
      ]
    },
    "Porazi2023": {
      "type": "string",
      "title": "The Porazi2023 Schema",
      "examples": [
        "56"
      ]
    },
    "Regija": {
      "type": "string",
      "title": "The Regija Schema",
      "examples": [
        "LCK"
      ]
    },
    "Ukupna_zarada": {
      "type": "string",
      "title": "The Ukupna_zarada Schema",
      "examples": [
        "9418521.00"
      ]
    },
    "Igraci": {
      "type": "array",
      "title": "The Igraci Schema",
      "items": {
        "type": "object",
        "title": "A Schema",
        "required": [
          "Ime",
          "Prezime",
          "Nickname",
          "Pozicija",
          "Godina_prikljucenja"
        ],
        "properties": {
          "Ime": {
            "type": "string",
            "title": "The Ime Schema",
            "examples": [
              "Lee"
            ]
          },
          "Prezime": {
            "type": "string",
            "title": "The Prezime Schema",
            "examples": [
              "Sang-hyeok"
            ]
          },
          "Nickname": {
            "type": "string",
            "title": "The Nickname Schema",
            "examples": [
              "Faker"
            ]
          },
          "Pozicija": {
            "type": "string",
            "title": "The Pozicija Schema",
            "examples": [
              "Mid"
            ]
          },
          "Godina_prikljucenja": {
            "type": "string",
            "title": "The Godina_prikljucenja Schema",
            "examples": [
              "2013"
            ]
          }
        },
        "examples": [
          {
            "Ime": "Lee",
            "Prezime": "Sang-hyeok",
            "Nickname": "Faker",
            "Pozicija": "Mid",
            "Godina_prikljucenja": "2013"
          }
        ]
      }
    }
  },
  "examples": [
    {
      "Naziv": "T1",
      "Zemlja": "Južna Koreja",
      "Godina_osnutka": "2003",
      "Skracenica": "T1",
      "Esport": "League of Legends",
      "Broj_trofeja": "10",
      "Pobjede2023": "96",
      "Porazi2023": "56",
      "Regija": "LCK",
      "Ukupna_zarada": "9418521.00",
      "Igraci": [
        {
          "Ime": "Lee",
          "Prezime": "Sang-hyeok",
          "Nickname": "Faker",
          "Pozicija": "Mid",
          "Godina_prikljucenja": "2013"
        },
        {
          "Ime": "Ryu",
          "Prezime": "Min-seok",
          "Nickname": "Zeus",
          "Pozicija": "Top",
          "Godina_prikljucenja": "2021"
        },
        {
          "Ime": "Moon",
          "Prezime": "Hyeon-jun",
          "Nickname": "Oner",
          "Pozicija": "Jungle",
          "Godina_prikljucenja": "2021"
        },
        {
          "Ime": "Lee",
          "Prezime": "Min-hyung",
          "Nickname": "Gumayusi",
          "Pozicija": "ADC",
          "Godina_prikljucenja": "2020"
        },
        {
          "Ime": "Ryu",
          "Prezime": "Min-seong",
          "Nickname": "Keria",
          "Pozicija": "Support",
          "Godina_prikljucenja": "2020"
        }
      ]
    }
  ]
}

=== barnikola/OTVRAC/lab3/timoviIgraci.json
[
  {
    "Naziv": "T1",
    "Zemlja": "Južna Koreja",
    "Godina_osnutka": "2003",
    "Skracenica": "T1",
    "Esport": "League of Legends",
    "Broj_trofeja": "10",
    "Pobjede2023": "96",
    "Porazi2023": "56",
    "Regija": "LCK",
    "Ukupna_zarada": "9418521.00",
    "Igraci": [
      {
        "Ime": "Lee",
        "Prezime": "Sang-hyeok",
        "Nickname": "Faker",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2013"
      },
      {
        "Ime": "Ryu",
        "Prezime": "Min-seok",
        "Nickname": "Zeus",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Moon",
        "Prezime": "Hyeon-jun",
        "Nickname": "Oner",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Lee",
        "Prezime": "Min-hyung",
        "Nickname": "Gumayusi",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Ryu",
        "Prezime": "Min-seong",
        "Nickname": "Keria",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2020"
      }
    ]
  },
  {
    "Naziv": "JD Gaming",
    "Zemlja": "Kina",
    "Godina_osnutka": "2017",
    "Skracenica": "JDG",
    "Esport": "League of Legends",
    "Broj_trofeja": "5",
    "Pobjede2023": "95",
    "Porazi2023": "30",
    "Regija": "LPL",
    "Ukupna_zarada": "2341588.00",
    "Igraci": [
      {
        "Ime": "Seo",
        "Prezime": "Jin-hyeok",
        "Nickname": "Kanavi",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Zhuo",
        "Prezime": "Ding",
        "Nickname": "Knight",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Park",
        "Prezime": "Jae-hyuk",
        "Nickname": "Ruler",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Bai",
        "Prezime": "Jiahao",
        "Nickname": "369",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Lou",
        "Prezime": "Yunfeng",
        "Nickname": "Missing",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2023"
      }
    ]
  },
  {
    "Naziv": "Gen.G",
    "Zemlja": "Južna Koreja",
    "Godina_osnutka": "2017",
    "Skracenica": "GEN",
    "Esport": "League of Legends",
    "Broj_trofeja": "3",
    "Pobjede2023": "95",
    "Porazi2023": "38",
    "Regija": "LCK",
    "Ukupna_zarada": "1943449.00",
    "Igraci": [
      {
        "Ime": "Han",
        "Prezime": "Wang-ho",
        "Nickname": "Peanut",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Jeong",
        "Prezime": "Ji-hoon",
        "Nickname": "Chovy",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Park",
        "Prezime": "Joon-young",
        "Nickname": "Doran",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Kim",
        "Prezime": "Tae-min",
        "Nickname": "Peyz",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Yoo",
        "Prezime": "Min-seok",
        "Nickname": "Delight",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2023"
      }
    ]
  },
  {
    "Naziv": "Bilibili Gaming",
    "Zemlja": "Kina",
    "Godina_osnutka": "2017",
    "Skracenica": "BLG",
    "Esport": "League of Legends",
    "Broj_trofeja": "2",
    "Pobjede2023": "100",
    "Porazi2023": "60",
    "Regija": "LPL",
    "Ukupna_zarada": "1442683.00",
    "Igraci": [
      {
        "Ime": "Chen",
        "Prezime": "Ze-Bin",
        "Nickname": "Bin",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Peng",
        "Prezime": "Zhen-Ming",
        "Nickname": "Xun",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Zeng",
        "Prezime": "Qi",
        "Nickname": "Yagao",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Elk",
        "Prezime": "",
        "Nickname": "Elk",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Liu",
        "Prezime": "Shi-Yu",
        "Nickname": "On",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2021"
      }
    ]
  },
  {
    "Naziv": "G2 Esports",
    "Zemlja": "Europa",
    "Godina_osnutka": "2014",
    "Skracenica": "G2",
    "Esport": "League of Legends",
    "Broj_trofeja": "9",
    "Pobjede2023": "68",
    "Porazi2023": "32",
    "Regija": "LEC",
    "Ukupna_zarada": "3603017.00",
    "Igraci": [
      {
        "Ime": "Sergen",
        "Prezime": "Çelik",
        "Nickname": "BrokenBlade",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Martin",
        "Prezime": "Hansen",
        "Nickname": "Yike",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Rasmus",
        "Prezime": "Winther",
        "Nickname": "Caps",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2018"
      },
      {
        "Ime": "Steven",
        "Prezime": "Liv",
        "Nickname": "Hans sama",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Mihael",
        "Prezime": "Mehle",
        "Nickname": "Mikyx",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2023"
      }
    ]
  },
  {
    "Naziv": "Fnatic",
    "Zemlja": "Europa",
    "Godina_osnutka": "2004",
    "Skracenica": "FNC",
    "Esport": "League of Legends",
    "Broj_trofeja": "7",
    "Pobjede2023": "37",
    "Porazi2023": "38",
    "Regija": "LEC",
    "Ukupna_zarada": "3480526.00",
    "Igraci": [
      {
        "Ime": "Óscar",
        "Prezime": "Muñoz",
        "Nickname": "Oscarinin",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Iván",
        "Prezime": "Martín",
        "Nickname": "Razork",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2022"
      },
      {
        "Ime": "Marek",
        "Prezime": "Brázda",
        "Nickname": "Humanoid",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2022"
      },
      {
        "Ime": "Carl",
        "Prezime": "Martin",
        "Nickname": "Rekkles",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2015"
      },
      {
        "Ime": "Adrian",
        "Prezime": "Trybus",
        "Nickname": "Trymbi",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2023"
      }
    ]
  },
  {
    "Naziv": "FlyQuest",
    "Zemlja": "SAD",
    "Godina_osnutka": "2017",
    "Skracenica": "FLY",
    "Esport": "League of Legends",
    "Broj_trofeja": "1",
    "Pobjede2023": "25",
    "Porazi2023": "23",
    "Regija": "LCS",
    "Ukupna_zarada": "497450.00",
    "Igraci": [
      {
        "Ime": "Jeong",
        "Prezime": "Ho-bin",
        "Nickname": "Impact",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Lucas",
        "Prezime": "Tao",
        "Nickname": "Santorin",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Loïc",
        "Prezime": "Dubois",
        "Nickname": "Toucouille",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2022"
      },
      {
        "Ime": "Bae",
        "Prezime": "Ho-min",
        "Nickname": "Prince",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Kim",
        "Prezime": "Dong-wook",
        "Nickname": "Winsome",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2023"
      }
    ]
  },
  {
    "Naziv": "Cloud9",
    "Zemlja": "SAD",
    "Godina_osnutka": "2013",
    "Skracenica": "C9",
    "Esport": "League of Legends",
    "Broj_trofeja": "6",
    "Pobjede2023": "50",
    "Porazi2023": "25",
    "Regija": "LCS",
    "Ukupna_zarada": "2662341.00",
    "Igraci": [
      {
        "Ime": "Ibrahim",
        "Prezime": "Allami",
        "Nickname": "Fudge",
        "Pozicija": "Top",
        "Godina_prikljucenja": "2021"
      },
      {
        "Ime": "Robert",
        "Prezime": "Huang",
        "Nickname": "Blaber",
        "Pozicija": "Jungle",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Jiang",
        "Prezime": "Tao",
        "Nickname": "Diplex",
        "Pozicija": "Mid",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Kim",
        "Prezime": "Min-cheol",
        "Nickname": "Berserker",
        "Pozicija": "ADC",
        "Godina_prikljucenja": "2023"
      },
      {
        "Ime": "Jesper",
        "Prezime": "Svenningsen",
        "Nickname": "Zven",
        "Pozicija": "Support",
        "Godina_prikljucenja": "2022"
      }
    ]
  },
  {
    "Naziv": "Sentinels",
    "Zemlja": "SAD",
    "Godina_osnutka": "2020",
    "Skracenica": "SEN",
    "Esport": "Valorant",
    "Broj_trofeja": "3",
    "Pobjede2023": "37",
    "Porazi2023": "30",
    "Regija": "NA",
    "Ukupna_zarada": "2500000.00",
    "Igraci": [
      {
        "Ime": "Hunter",
        "Prezime": "Mims",
        "Nickname": "SicK",
        "Pozicija": "Flex",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Jared",
        "Prezime": "Gitlin",
        "Nickname": "zombs",
        "Pozicija": "Controller",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Shahzeeb",
        "Prezime": "Khan",
        "Nickname": "ShahZaM",
        "Pozicija": "In-game Leader",
        "Godina_prikljucenja": "2020"
      },
      {
        "Ime": "Tyson",
        "Prezime": "Ngo",
        "Nickname": "TenZ",
        "Pozicija": "Duelist",
        "Godina_prikljucenja": "2021"
      },
      {
